#! /bin/bash

case $1 in
  "" )
    echo "Hello $USER!&!&!";;
   "$1")
    echo "Hello $1!&!&!";;
    echo "My name is $1!&!&!";;
    echo "Your name is $1!&!&!";;
    echo "Test pull request!!";;
esac
